title: theonchained
description: " Unlocking Africa's Real-World Wealth Through Blockchain"
footer_text: Africa’s Assets Are Going On-Chain
header_feature_image: ../uploads/img_0352.jpg
header_text: My Dream Blog
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/logo.png
favicon: ../uploads/logo.png
gridlayout: false
fixednavbar: false
upzoom: true
